import streamlit as st
import pandas as pd
import plotly.express as px

st.set_page_config(
    page_title="RENENSP WBE Observatory",
    layout="wide"
)

st.title("RENENSP")

st.caption(
    "Northeast Network for the Production of Secondary Reference Standards and Monitoring of New Psychoactive Substance Consumption through Wastewater-Based Epidemiology"
)

st.info(
    """
    The RENENSP Network is a collaborative initiative focused on monitoring classical drugs and new psychoactive substances (NPS) through wastewater-based epidemiology (WBE) across Northeast Brazil.

    This public platform provides open-access data generated by the network to support research, innovation, public health actions, and evidence-based policies.
    """
)
@st.cache_data
def load_data():
    try:
        df = pd.read_csv("renensp.csv", sep=",")
    except Exception:
        df = pd.read_csv("renensp.csv", sep="\t")

    # If it read everything as one column, try TAB
    if len(df.columns) == 1:
        df = pd.read_csv("renensp.csv", sep="\t")

    df = df.dropna(how="all")
    df.columns = df.columns.str.strip()

    df["Sampling_Date"] = pd.to_datetime(df["Sampling_Date"], errors="coerce")
    df["Event_Day"] = pd.to_numeric(df["Event_Day"], errors="coerce")
    df["PNML_mg_day_1000inh"] = pd.to_numeric(df["PNML_mg_day_1000inh"], errors="coerce")
    df["Load_g_day"] = pd.to_numeric(df["Load_g_day"], errors="coerce")

    return df
    
df = load_data()

state_coords = pd.DataFrame({
    "State": ["PE", "PB", "RN"],
    "State_Name": ["Pernambuco", "Paraíba", "Rio Grande do Norte"],
    "lat": [-8.0476, -7.1195, -5.7945],
    "lon": [-34.8770, -34.8450, -35.2110]
})

map_data = (
    df.groupby("State")
    .size()
    .reset_index(name="Records")
    .merge(state_coords, on="State", how="left")
)

st.sidebar.image(
    "logo_renensp.png",
    use_container_width=True
)

st.sidebar.header("Filters")

state = st.sidebar.multiselect("State", sorted(df["State"].dropna().unique()))
city = st.sidebar.multiselect("City", sorted(df["City"].dropna().unique()))
event = st.sidebar.multiselect("Event", sorted(df["Event"].dropna().unique()))
period = st.sidebar.multiselect("Period", sorted(df["Period"].dropna().unique()))
platform = st.sidebar.multiselect("Analytical Platform", sorted(df["Analytical_Platform"].dropna().unique()))
analysis = st.sidebar.multiselect("Analysis Type", sorted(df["Analysis_Type"].dropna().unique()))
drug_class = st.sidebar.multiselect("Drug Class", sorted(df["Drug_Class"].dropna().unique()))
substance = st.sidebar.multiselect("Substance", sorted(df["Substance"].dropna().unique()))

filtered = df.copy()

if state:
    filtered = filtered[filtered["State"].isin(state)]
if city:
    filtered = filtered[filtered["City"].isin(city)]
if event:
    filtered = filtered[filtered["Event"].isin(event)]
if period:
    filtered = filtered[filtered["Period"].isin(period)]
if platform:
    filtered = filtered[filtered["Analytical_Platform"].isin(platform)]
if analysis:
    filtered = filtered[filtered["Analysis_Type"].isin(analysis)]
if drug_class:
    filtered = filtered[filtered["Drug_Class"].isin(drug_class)]
if substance:
    filtered = filtered[filtered["Substance"].isin(substance)]

st.header("Overview")

col1, col2, col3, col4, col5 = st.columns(5)

col1.metric("Records", len(filtered))
col2.metric("States", filtered["State"].nunique())
col3.metric("Cities", filtered["City"].nunique())
col4.metric("Substances", filtered["Substance"].nunique())
col5.metric("Events", filtered["Event"].nunique())

tab1, tab2, tab3, tab4, tab5 = st.tabs([
    "Interactive Map",
    "Dashboard",
    "Target Quantification",
    "NPS Screening",
    "Data Table"
])

with tab1:
    st.subheader("Monitored States")
    st.info("Use the mouse wheel, double click, or the zoom buttons to explore the map.")

    fig_map = px.scatter_mapbox(
        map_data,
        lat="lat",
        lon="lon",
        size="Records",
        color="State",
        hover_name="State_Name",
        hover_data={"Records": True, "lat": False, "lon": False},
        zoom=5,
        height=650,
        title="RENENSP Monitoring Coverage"
    )

    fig_map.update_layout(
        mapbox_style="open-street-map",
        dragmode="zoom",
        mapbox=dict(
            center=dict(lat=-7.2, lon=-36.0),
            zoom=5
        ),
        margin={"r": 0, "t": 40, "l": 0, "b": 0}
    )

    st.plotly_chart(
        fig_map,
        use_container_width=True,
        config={
            "scrollZoom": True,
            "displayModeBar": True,
            "displaylogo": False
        }
    )

with tab2:
    st.subheader("General Dashboard")

    if len(filtered) > 0:
        colA, colB = st.columns(2)

        with colA:
            fig1 = px.histogram(
                filtered,
                x="Substance",
                color="Analysis_Type",
                title="Records by Substance"
            )
            st.plotly_chart(fig1, use_container_width=True)

        with colB:
            fig2 = px.histogram(
                filtered,
                x="Event",
                color="State",
                title="Records by Event and State"
            )
            st.plotly_chart(fig2, use_container_width=True)

        colC, colD = st.columns(2)

        with colC:
            fig3 = px.histogram(
                filtered,
                x="Period",
                color="Detection",
                title="Detection by Period"
            )
            st.plotly_chart(fig3, use_container_width=True)

        with colD:
            fig4 = px.histogram(
                filtered,
                x="Analytical_Platform",
                color="Analysis_Type",
                title="Analytical Platform Overview"
            )
            st.plotly_chart(fig4, use_container_width=True)

    else:
        st.warning("No data available for the selected filters.")

with tab3:
    st.subheader("Target Quantification – Triple Quadrupole MS/MS")

    quant = filtered[filtered["Analysis_Type"] == "Quantification"]

    if len(quant) > 0:

        tab_load, tab_pnml = st.tabs([
            "Load (g/day)",
            "PNML (mg/day/1000 inhabitants)"
        ])

        with tab_load:
            fig_load = px.bar(
                quant,
                x="Event",
                y="Load_g_day",
                color="Substance",
                barmode="group",
                title="Daily Load by Event",
                labels={
                    "Event": "Event",
                    "Load_g_day": "Load (g/day)",
                    "Substance": "Substance"
                }
            )

            st.plotly_chart(fig_load, use_container_width=True)

        with tab_pnml:
            fig_pnml = px.bar(
                quant,
                x="Event",
                y="PNML_mg_day_1000inh",
                color="Substance",
                barmode="group",
                title="Population-Normalized Mass Load by Event",
                labels={
                    "Event": "Event",
                    "PNML_mg_day_1000inh": "PNML (mg/day/1000 inhabitants)",
                    "Substance": "Substance"
                }
            )

            st.plotly_chart(fig_pnml, use_container_width=True)

        st.markdown("### Complete Quantification Dataset")
        st.dataframe(quant, use_container_width=True)

    else:
        st.info("No quantification data available for the selected filters.")
with tab4:
    st.subheader("NPS Screening – Orbitrap HRMS")

    screening = filtered[filtered["Analysis_Type"] == "Screening"]

    if len(screening) > 0:
        detected = screening[screening["Detection"] == "Detected"]

        fig7 = px.histogram(
            detected,
            x="Substance",
            color="Event",
            title="Detected NPS by Event"
        )
        st.plotly_chart(fig7, use_container_width=True)

        detection_frequency = (
            screening
            .groupby(["Substance", "Detection"])
            .size()
            .reset_index(name="Count")
        )

        fig8 = px.bar(
            detection_frequency,
            x="Substance",
            y="Count",
            color="Detection",
            title="Screening Detection Frequency"
        )
        st.plotly_chart(fig8, use_container_width=True)

        heatmap_data = (
            screening
            .assign(Detected_Num=screening["Detection"].eq("Detected").astype(int))
            .pivot_table(
                index="Substance",
                columns="Event",
                values="Detected_Num",
                aggfunc="sum",
                fill_value=0
            )
        )

        fig9 = px.imshow(
            heatmap_data,
            text_auto=True,
            aspect="auto",
            title="NPS Detection Heatmap by Event"
        )
        st.plotly_chart(fig9, use_container_width=True)

        st.dataframe(screening, use_container_width=True)
    else:
        st.info("No screening data available for the selected filters.")

with tab5:
    st.subheader("Complete Dataset")

    st.dataframe(filtered, use_container_width=True)

    csv = filtered.to_csv(index=False).encode("utf-8")

    st.download_button(
        label="Download filtered data as CSV",
        data=csv,
        file_name="renensp_filtered_data.csv",
        mime="text/csv"
    )
