@st.cache_data
def load_data():
    separators = [",", "\t", ";"]
    df = None

    for sep in separators:
        temp = pd.read_csv("renensp.csv", sep=sep)
        temp.columns = temp.columns.str.strip()

        if "Year" in temp.columns and "State" in temp.columns and "Period" in temp.columns:
            df = temp
            break

    if df is None:
        st.error("The file renensp.csv was not read correctly. Check if the separator is comma, tab, or semicolon.")
        st.stop()

    df = df.dropna(how="all")
    df.columns = df.columns.str.strip()

    required_columns = [
        "Year", "State", "City", "WWTP", "Event", "Sampling_Date",
        "Event_Day", "Period", "Substance", "Drug_Class",
        "Analytical_Platform", "Analysis_Type", "Detection",
        "Population_NH4N", "Load_g_day", "PNML_mg_day_1000inh"
    ]

    missing = [col for col in required_columns if col not in df.columns]

    if missing:
        st.error(f"Missing columns in renensp.csv: {missing}")
        st.stop()

    df["Sampling_Date"] = pd.to_datetime(df["Sampling_Date"], errors="coerce")
    df["Year"] = pd.to_numeric(df["Year"], errors="coerce").astype("Int64")
    df["Event_Day"] = pd.to_numeric(df["Event_Day"], errors="coerce")
    df["Population_NH4N"] = pd.to_numeric(df["Population_NH4N"], errors="coerce")
    df["Load_g_day"] = pd.to_numeric(df["Load_g_day"], errors="coerce")
    df["PNML_mg_day_1000inh"] = pd.to_numeric(df["PNML_mg_day_1000inh"], errors="coerce")

    text_cols = [
        "State", "City", "WWTP", "Event", "Period", "Substance",
        "Drug_Class", "Analytical_Platform", "Analysis_Type", "Detection"
    ]

    for col in text_cols:
        df[col] = df[col].astype(str).str.strip()
        df[col] = df[col].replace({"nan": None, "None": None, "": None})

return df

df = load_data() 
 
# ============================================================
# SUPPORT FUNCTIONS
# ============================================================
 
def unique_sorted(dataframe, column):
    values = dataframe[column].dropna().unique().tolist()
    return sorted(values)
 
 
def format_int(value):
    if pd.isna(value):
        return "NA"
    return f"{int(value):,}"
 
 
def event_specific_population(dataframe):
    """
    Population is not fixed by city. It depends on year, event and WWTP.
    Because each substance repeats the same Population_NH4N for the same sampling context,
    we deduplicate before summarizing population.
    """
    if len(dataframe) == 0 or "Population_NH4N" not in dataframe.columns:
        return None
 
    keys = ["Year", "State", "City", "WWTP", "Event"]
    pop = (
        dataframe.dropna(subset=["Population_NH4N"])
        .drop_duplicates(subset=keys)
        ["Population_NH4N"]
        .sum()
    )
 
    if pd.isna(pop) or pop == 0:
        return None
 
    return pop
 
 
def get_population_table(dataframe):
    keys = ["Year", "State", "City", "WWTP", "Event"]
    return (
        dataframe.dropna(subset=["Population_NH4N"])
        .groupby(keys, as_index=False)["Population_NH4N"]
        .max()
        .sort_values(keys)
    )
 
 
# ============================================================
# HEADER
# ============================================================
 
st.title("RENENSP")
 
st.caption(
    "Northeast Network for the Production of Secondary Reference Standards and Monitoring of "
    "New Psychoactive Substance Consumption through Wastewater-Based Epidemiology"
)
 
st.info(
    """
    The RENENSP Network is a collaborative initiative focused on monitoring classical drugs and
    new psychoactive substances (NPS) through wastewater-based epidemiology (WBE) across Northeast Brazil.
 
    This public platform provides open-access data generated by the network to support research,
    innovation, public health actions, and evidence-based policies.
    """
)
 
st.markdown("🔗 **PEM Research Group:** [@grupo.pem](https://www.instagram.com/grupo.pem/)")
 
 
# ============================================================
# SIDEBAR
# ============================================================
 
try:
    st.sidebar.image("logo_renensp.png", use_container_width=True)
except Exception:
    st.sidebar.warning("Logo file not found: logo_renensp.png")
 
st.sidebar.header("Additional filters")
 
# These are secondary filters. The main scientific navigation is in the Data Navigation panel below.
substance_filter = st.sidebar.multiselect("Substance", unique_sorted(df, "Substance"))
drug_class_filter = st.sidebar.multiselect("Drug Class", unique_sorted(df, "Drug_Class"))
platform_filter = st.sidebar.multiselect("Analytical Platform", unique_sorted(df, "Analytical_Platform"))
analysis_filter = st.sidebar.multiselect("Analysis Type", unique_sorted(df, "Analysis_Type"))
detection_filter = st.sidebar.multiselect("Detection", unique_sorted(df, "Detection"))
 
 
# ============================================================
# CASCADE NAVIGATION
# ============================================================
 
st.header("Data Navigation")
 
st.markdown(
    """
    Use the cascade below to navigate the monitoring results by **year**, **state**, **WWTP**,
    **event**, **period** and **analysis type**. Population estimates are treated as
    **year-, event- and WWTP-specific**, because the population covered by each wastewater
    sampling campaign can change across time and sites.
    """
)
 
nav1, nav2, nav3 = st.columns(3)
 
with nav1:
    year_options = ["All"] + [str(int(y)) for y in unique_sorted(df.dropna(subset=["Year"]), "Year")]
    selected_year = st.selectbox("1. Select year", year_options)
 
df_year = df.copy()
if selected_year != "All":
    df_year = df_year[df_year["Year"] == int(selected_year)]
 
with nav2:
    state_options = ["All"] + unique_sorted(df_year, "State")
    selected_state = st.selectbox("2. Select state", state_options)
 
df_state = df_year.copy()
if selected_state != "All":
    df_state = df_state[df_state["State"] == selected_state]
 
with nav3:
    city_options = ["All"] + unique_sorted(df_state, "City")
    selected_city = st.selectbox("3. Select city", city_options)
 
df_city = df_state.copy()
if selected_city != "All":
    df_city = df_city[df_city["City"] == selected_city]
 
nav4, nav5, nav6 = st.columns(3)
 
with nav4:
    wwtp_options = ["All"] + unique_sorted(df_city, "WWTP")
    selected_wwtp = st.selectbox("4. Select WWTP", wwtp_options)
 
df_wwtp = df_city.copy()
if selected_wwtp != "All":
    df_wwtp = df_wwtp[df_wwtp["WWTP"] == selected_wwtp]
 
with nav5:
    event_options = ["All"] + unique_sorted(df_wwtp, "Event")
    selected_event = st.selectbox("5. Select event", event_options)
 
df_event = df_wwtp.copy()
if selected_event != "All":
    df_event = df_event[df_event["Event"] == selected_event]
 
with nav6:
    period_options = unique_sorted(df_event, "Period")
    selected_periods = st.multiselect("6. Select period", period_options, default=period_options)
 
filtered = df_event.copy()
if selected_periods:
    filtered = filtered[filtered["Period"].isin(selected_periods)]
 
# Apply sidebar filters
if substance_filter:
    filtered = filtered[filtered["Substance"].isin(substance_filter)]
if drug_class_filter:
    filtered = filtered[filtered["Drug_Class"].isin(drug_class_filter)]
if platform_filter:
    filtered = filtered[filtered["Analytical_Platform"].isin(platform_filter)]
if analysis_filter:
    filtered = filtered[filtered["Analysis_Type"].isin(analysis_filter)]
if detection_filter:
    filtered = filtered[filtered["Detection"].isin(detection_filter)]
 
 
# ============================================================
# OVERVIEW METRICS
# ============================================================
 
st.header("Overview")
 
detected_nps = filtered[
    (filtered["Analysis_Type"] == "Screening") &
    (filtered["Detection"] == "Detected")
]
 
population_covered = event_specific_population(filtered)
 
col1, col2, col3, col4, col5, col6, col7, col8 = st.columns(8)
 
col1.metric("Monitoring results", len(filtered))
col2.metric("Years", filtered["Year"].nunique())
col3.metric("States", filtered["State"].nunique())
col4.metric("Cities", filtered["City"].nunique())
col5.metric("WWTPs", filtered["WWTP"].nunique())
col6.metric("Events", filtered["Event"].nunique())
col7.metric("Detected NPS", detected_nps["Substance"].nunique())
col8.metric("Population covered", format_int(population_covered))
 
st.caption(
    "Population covered is calculated from unique year–state–city–WWTP–event combinations, "
    "avoiding repeated counts across substances from the same sampling context."
)
 
 
# ============================================================
# TABS
# ============================================================
 
tab_about, tab_partners, tab_map, tab_dashboard, tab_population, tab_classical, tab_nps, tab_events, tab_method, tab_data = st.tabs([
    "About the Project",
    "Partner Institutions",
    "Interactive Map",
    "Dashboard",
    "Population",
    "Classical Drugs",
    "NPS Observatory",
    "Events",
    "Methodology",
    "Data Explorer"
])
 
 
# ============================================================
# ABOUT
# ============================================================
 
with tab_about:
    st.subheader("About the RENENSP Project")
 
    st.markdown(
        """
        **Project title:**  
        Northeast Network for the Production of Secondary Reference Standards and Monitoring of New Psychoactive
        Substance Consumption through Wastewater-Based Epidemiology – RENENSP
 
        **Original title in Portuguese:**  
        Rede Nordeste de produção de padrões secundários e monitoramento do consumo através da epidemiologia do esgoto
        de novas substâncias psicoativas – RENENSP
 
        **Funding call:**  
        PROCAD – Academic Cooperation Support Action – Drug Policies  
        Joint Call No. 2/2024 – CAPES/SENAD
 
        **Proponent institution:**  
        Federal Rural University of Pernambuco (UFRPE)
 
        **Graduate program:**  
        Graduate Program in Chemistry – UFRPE
 
        **Project period:**  
        November 2024 to October 2029
 
        **Duration:**  
        60 months
 
        **Knowledge area:**  
        Chemistry
 
        **Thematic axis:**  
        Axis 2 – New Psychoactive Substances (NPS)
 
        ### Project description
 
        RENENSP aims to establish an academic and scientific cooperation network involving higher education institutions
        and public security agencies. The project focuses on two main goals: the production of secondary reference
        standards for new psychoactive substances and the monitoring of NPS consumption through wastewater-based
        epidemiology in Northeast Brazil.
 
        The project targets festive and non-festive periods, including Carnival, São João Festival, New Year's Eve and
        reference weeks, providing scientific evidence to support public health, public security and evidence-based drug
        policies.
 
        ### General objective
 
        To create an academic and scientific cooperation network to develop secondary reference standards and monitor
        the consumption of new psychoactive substances through wastewater-based epidemiology in Northeast Brazil.
 
        ### Specific objectives
 
        - Produce secondary reference standards of NPS from materials seized by public security agencies, focusing on
          synthetic cathinones, synthetic cannabinoids and synthetic opioids.
        - Characterize secondary reference standards using chromatographic, spectrometric and spectroscopic techniques,
          such as GC/MS, LC/MS and NMR.
        - Collect and prepare raw wastewater samples from wastewater treatment plants during non-festive days and festive
          events in Northeast Brazil.
        - Develop instrumental methods by GC/MS, LC/MS and NMR for NPS.
        - Monitor the emergence of NPS during different sampling periods and identify consumption trends and affected regions.
        - Expand human resource training through scientific research and cooperation with public security institutions.
 
        ### Expected impact
 
        - Monitoring the emergence and consumption of NPS in Northeast Brazil.
        - Supporting public health and public security strategies.
        - Producing secondary reference standards from seized materials.
        - Strengthening forensic and environmental analytical capacity.
        - Training human resources in analytical chemistry, forensic toxicology and wastewater-based epidemiology.
        """
    )
 
    st.markdown("---")
 
    st.subheader("Platform Information")
 
    st.markdown(
        """
        **RENENSP Observatory**
 
        Developed under the PROCAD CAPES/SENAD Project.
 
        ### Project Coordination
 
        **Prof. Dr. Jandyson Machado Santos**  
        Federal Rural University of Pernambuco (UFRPE)  
        📧 jandyson.machado@ufrpe.br
 
        ### Platform Development
 
        **Dr. Bruna Ramos de Souza Gomes**  
        Platform Developer  
        📧 brunaramosquimica@gmail.com
 
        ### Research Group
 
        **PEM – Petroleum, Energy and Mass Spectrometry Research Group**  
        Instagram: [@grupo.pem](https://www.instagram.com/grupo.pem/)
 
        © RENENSP Network – 2026
        """
    )
 
 
# ============================================================
# PARTNERS
# ============================================================
 
with tab_partners:
    st.subheader("Partner Institutions and Research Team")
 
    st.markdown(
        """
        ### Coordination
 
        **Principal Coordinator:**  
        Jandyson Machado Santos – PPGQ/UFRPE
 
        **Associate Coordinator:**  
        Josean Fechine Tavares – PgPNSB/UFPB
 
        ### Proponent Institution
 
        **Federal Rural University of Pernambuco (UFRPE)**  
        Graduate Program in Chemistry
 
        ### Partner Teams
 
        - Adriana Santos Ribeiro – PGMateriais/UFAL
        - Alberto Wisniewski Jr – PPGQ/UFS
        - Alexandro M. L. de Assis – Federal Police/AL and PGMateriais/UFAL
        - Beate Saegesser Santos – Department of Pharmacy/UFPE
        - Cezar Silvino Gomes – Federal Police/PB
        - Cícero Flávio Soares Aragão – Department of Pharmacy/UFRN
        - Cíntia Maria do Rego Barros Veiga – Scientific Police Institute/PB
        - Elaine Andrade de Oliveira Bezerra – Scientific Police Institute/PB
        - Marcos José Brandão Guimarães – Technical-Scientific Institute of Forensics/RN
        - Mônica Paulo de Souza – Federal Police/PB
        - Ricardo Saldanha Honorato – Federal Police/PE
        - Rosana Coutinho Freire Silva – Scientific Police of Alagoas
        - Socrates Golzio dos Santos – Department of Pharmacy/UFPB
 
        ### Institutional and scientific scope
 
        RENENSP integrates higher education institutions, graduate programs, forensic laboratories and public security
        institutions to strengthen scientific and technological capacity for monitoring NPS in Northeast Brazil.
 
        ### Keywords
 
        New psychoactive substances; Secondary reference standards; Wastewater-based epidemiology; Northeast Brazil;
        Consumption patterns; Drug policies.
        """
    )
 
    st.markdown("---")
 
    st.subheader("Contact")
 
    st.markdown(
        """
        ### Project Coordinator
 
        **Prof. Dr. Jandyson Machado Santos**  
        📧 jandyson.machado@ufrpe.br
 
        ### Platform Developer
 
        **Dr. Bruna Ramos de Souza Gomes**  
        📧 brunaramosquimica@gmail.com
 
        ### Research Group
 
        **PEM – Petroleum, Energy and Mass Spectrometry Research Group**  
        Instagram: [@grupo.pem](https://www.instagram.com/grupo.pem/)
        """
    )
 
 
# ============================================================
# MAP
# ============================================================
 
with tab_map:
    st.subheader("Interactive Monitoring Map")
    st.info("Use the mouse wheel, double click, or zoom buttons to explore the map.")
 
    # Coordinates can be expanded as new WWTPs are added.
    wwtp_coords = pd.DataFrame({
        "State": ["PE", "PE", "PB", "PB", "RN", "AL", "SE", "CE", "BA"],
        "City": ["Recife", "Olinda", "Joao Pessoa", "Campina Grande", "Natal", "Maceio", "Aracaju", "Fortaleza", "Salvador"],
        "WWTP": ["Cabanga", "Peixinho", "Mangabeira", "Catingueira", "Jundiai-Guarapes", "Benedito Bentes", "Orlando Dantas", "Coco", "Boca do Rio"],
        "lat": [-8.071, -7.999, -7.175, -7.2307, -5.7945, -9.6498, -10.9472, -3.7319, -12.9777],
        "lon": [-34.884, -34.860, -34.845, -35.8817, -35.2110, -35.7089, -37.0731, -38.5267, -38.5016],
    })
 
    map_data = (
        filtered.groupby(["Year", "State", "City", "WWTP"], as_index=False)
        .agg(
            Monitoring_Results=("Substance", "count"),
            Population_NH4N=("Population_NH4N", "max")
        )
        .merge(wwtp_coords, on=["State", "City", "WWTP"], how="left")
    )
 
    missing_coords = map_data[map_data["lat"].isna()]
    if len(missing_coords) > 0:
        st.warning(
            "Some WWTPs do not have coordinates yet. Add them to the wwtp_coords table in app.py to display them on the map."
        )
 
    map_data = map_data.dropna(subset=["lat", "lon"])
 
    if len(map_data) > 0:
        fig_map = px.scatter_mapbox(
            map_data,
            lat="lat",
            lon="lon",
            size="Monitoring_Results",
            color="State",
            hover_name="WWTP",
            hover_data={
                "Year": True,
                "State": True,
                "City": True,
                "Monitoring_Results": True,
                "Population_NH4N": True,
                "lat": False,
                "lon": False,
            },
            zoom=5,
            height=650,
            title="RENENSP monitoring coverage by WWTP"
        )
 
        fig_map.update_layout(
            mapbox_style="open-street-map",
            dragmode="zoom",
            mapbox=dict(center=dict(lat=-7.8, lon=-37.2), zoom=4.5),
            margin={"r": 0, "t": 40, "l": 0, "b": 0}
        )
 
        st.plotly_chart(
            fig_map,
            use_container_width=True,
            config={"scrollZoom": True, "displayModeBar": True, "displaylogo": False}
        )
    else:
        st.info("No mapped WWTPs available for the selected filters.")
 
 
# ============================================================
# DASHBOARD
# ============================================================
 
with tab_dashboard:
    st.subheader("General Dashboard")
 
    if len(filtered) > 0:
        colA, colB = st.columns(2)
 
        with colA:
            fig = px.histogram(
                filtered,
                x="Substance",
                color="Analysis_Type",
                title="Monitoring results by substance"
            )
            st.plotly_chart(fig, use_container_width=True)
 
        with colB:
            fig = px.histogram(
                filtered,
                x="WWTP",
                color="State",
                title="Monitoring results by WWTP"
            )
            st.plotly_chart(fig, use_container_width=True)
 
        colC, colD = st.columns(2)
 
        with colC:
            fig = px.histogram(
                filtered,
                x="Event",
                color="Year",
                title="Monitoring results by event and year"
            )
            st.plotly_chart(fig, use_container_width=True)
 
        with colD:
            fig = px.histogram(
                filtered,
                x="Period",
                color="Detection",
                title="Detection by period"
            )
            st.plotly_chart(fig, use_container_width=True)
 
    else:
        st.warning("No data available for the selected filters.")
 
 
# ============================================================
# POPULATION
# ============================================================
 
with tab_population:
    st.subheader("Population Estimated by NH4-N")
 
    st.info(
        """
        Population_NH4N represents the estimated population used for normalization of wastewater-based indicators.
        In this dashboard, population is treated as **year-, event- and WWTP-specific**, because the covered population
        may change between campaigns, years and wastewater treatment plants.
        """
    )
 
    pop_table = get_population_table(filtered)
 
    if len(pop_table) > 0:
        fig_pop_wwtp = px.bar(
            pop_table,
            x="WWTP",
            y="Population_NH4N",
            color="Year",
            barmode="group",
            facet_col="State",
            title="Estimated Population by WWTP and Year",
            labels={"Population_NH4N": "Estimated population (NH4-N)"}
        )
        st.plotly_chart(fig_pop_wwtp, use_container_width=True)
 
        fig_pop_event = px.bar(
            pop_table,
            x="Event",
            y="Population_NH4N",
            color="WWTP",
            barmode="group",
            title="Estimated Population by Event and WWTP",
            labels={"Population_NH4N": "Estimated population (NH4-N)"}
        )
        st.plotly_chart(fig_pop_event, use_container_width=True)
 
        st.markdown("### Population Summary")
        st.dataframe(pop_table, use_container_width=True)
 
    else:
        st.info("No population data available for the selected filters.")
 
 
# ============================================================
# CLASSICAL DRUGS
# ============================================================
 
with tab_classical:
    st.subheader("Classical Drugs – Target Quantification")
 
    quant = filtered[filtered["Analysis_Type"] == "Quantification"]
 
    if len(quant) > 0:
        tab_load, tab_pnml, tab_trends = st.tabs([
            "Load (g/day)",
            "PNML (mg/day/1000 inhabitants)",
            "Temporal Trends"
        ])
 
        with tab_load:
            fig_load = px.bar(
                quant,
                x="Event",
                y="Load_g_day",
                color="Substance",
                barmode="group",
                facet_col="Year",
                title="Daily Load by Event and Year",
                labels={"Load_g_day": "Load (g/day)"}
            )
            st.plotly_chart(fig_load, use_container_width=True)
 
            fig_wwtp_load = px.bar(
                quant.groupby(["Year", "State", "WWTP", "Substance"], as_index=False)["Load_g_day"].sum(),
                x="WWTP",
                y="Load_g_day",
                color="Substance",
                barmode="group",
                facet_col="Year",
                title="Total Load by WWTP and Year",
                labels={"Load_g_day": "Total Load (g/day)"}
            )
            st.plotly_chart(fig_wwtp_load, use_container_width=True)
 
        with tab_pnml:
            fig_pnml = px.bar(
                quant,
                x="Event",
                y="PNML_mg_day_1000inh",
                color="Substance",
                barmode="group",
                facet_col="Year",
                title="Population-Normalized Mass Load by Event and Year",
                labels={"PNML_mg_day_1000inh": "PNML (mg/day/1000 inhabitants)"}
            )
            st.plotly_chart(fig_pnml, use_container_width=True)
 
            fig_wwtp_pnml = px.bar(
                quant.groupby(["Year", "State", "WWTP", "Substance"], as_index=False)["PNML_mg_day_1000inh"].mean(),
                x="WWTP",
                y="PNML_mg_day_1000inh",
                color="Substance",
                barmode="group",
                facet_col="Year",
                title="Average PNML by WWTP and Year",
                labels={"PNML_mg_day_1000inh": "Average PNML"}
            )
            st.plotly_chart(fig_wwtp_pnml, use_container_width=True)
 
        with tab_trends:
            temporal = quant.dropna(subset=["Event_Day", "PNML_mg_day_1000inh"])
 
            if temporal["Event_Day"].nunique() > 1:
                fig_trend = px.line(
                    temporal.sort_values("Event_Day"),
                    x="Event_Day",
                    y="PNML_mg_day_1000inh",
                    color="Substance",
                    line_dash="Event",
                    markers=True,
                    facet_col="WWTP",
                    title="Temporal profile around events by WWTP",
                    labels={
                        "Event_Day": "Event day",
                        "PNML_mg_day_1000inh": "PNML (mg/day/1000 inhabitants)"
                    }
                )
                st.plotly_chart(fig_trend, use_container_width=True)
            else:
                st.info(
                    "Temporal trends will be more informative when the dataset includes multiple event days, "
                    "such as -4, -3, -2, -1, 0, +1 and +2."
                )
 
        st.markdown("### Complete Quantification Dataset")
        st.dataframe(quant, use_container_width=True)
 
    else:
        st.info("No quantification data available for the selected filters.")
 
 
# ============================================================
# NPS OBSERVATORY
# ============================================================
 
with tab_nps:
    st.subheader("NPS Observatory – Orbitrap HRMS Screening")
 
    screening = filtered[filtered["Analysis_Type"] == "Screening"]
 
    if len(screening) > 0:
        detected = screening[screening["Detection"] == "Detected"]
 
        colA, colB = st.columns(2)
 
        with colA:
            fig = px.histogram(
                detected,
                x="Substance",
                color="Event",
                title="Detected NPS by Event"
            )
            st.plotly_chart(fig, use_container_width=True)
 
        with colB:
            detection_frequency = (
                screening.groupby(["Substance", "Detection"])
                .size()
                .reset_index(name="Count")
            )
 
            fig = px.bar(
                detection_frequency,
                x="Substance",
                y="Count",
                color="Detection",
                title="NPS Detection Frequency"
            )
            st.plotly_chart(fig, use_container_width=True)
 
        heatmap_data = (
            screening
            .assign(Detected_Num=screening["Detection"].eq("Detected").astype(int))
            .pivot_table(
                index="Substance",
                columns=["Year", "Event"],
                values="Detected_Num",
                aggfunc="sum",
                fill_value=0
            )
        )
 
        fig_heatmap = px.imshow(
            heatmap_data,
            text_auto=True,
            aspect="auto",
            title="NPS Detection Heatmap by Year and Event"
        )
        st.plotly_chart(fig_heatmap, use_container_width=True)
 
        st.markdown("### NPS Screening Dataset")
        st.dataframe(screening, use_container_width=True)
 
    else:
        st.info("No screening data available for the selected filters.")
 
 
# ============================================================
# EVENTS
# ============================================================
 
with tab_events:
    st.subheader("Event Comparison")
 
    if len(filtered) > 0:
        event_overview = (
            filtered.groupby(["Year", "Event", "State", "WWTP"])
            .agg(
                Monitoring_Results=("Event", "count"),
                Substances=("Substance", "nunique"),
                Cities=("City", "nunique"),
                Population=("Population_NH4N", "max")
            )
            .reset_index()
        )
 
        fig_event = px.bar(
            event_overview,
            x="Event",
            y="Monitoring_Results",
            color="State",
            barmode="group",
            facet_col="Year",
            title="Monitoring results by event, state and year"
        )
        st.plotly_chart(fig_event, use_container_width=True)
 
        quant_events = filtered[filtered["Analysis_Type"] == "Quantification"]
 
        if len(quant_events) > 0:
            fig_compare = px.bar(
                quant_events,
                x="Event",
                y="PNML_mg_day_1000inh",
                color="Substance",
                barmode="group",
                facet_col="Year",
                title="Quantified substances across events and years",
                labels={"PNML_mg_day_1000inh": "PNML"}
            )
            st.plotly_chart(fig_compare, use_container_width=True)
 
        st.dataframe(event_overview, use_container_width=True)
 
    else:
        st.info("No event data available for the selected filters.")
 
 
# ============================================================
# METHODOLOGY
# ============================================================
 
with tab_method:
    st.subheader("Methodology")
 
    st.markdown(
        """
        ### Wastewater-Based Epidemiology
 
        Wastewater-based epidemiology (WBE) estimates community-level exposure or consumption of chemical substances
        by measuring biomarkers, parent compounds, or transformation products in wastewater samples.
 
        ### Analytical Platforms
 
        **Triple Quadrupole MS/MS** is used for target quantification of selected substances.
        This allows the estimation of daily loads and population-normalized mass loads.
 
        **Orbitrap HRMS** is used for screening of new psychoactive substances (NPS).
        This approach supports suspect screening and qualitative detection of emerging substances.
 
        ### Main Indicators
 
        **WWTP** identifies the wastewater treatment plant or sampling site.
 
        **Population_NH4N** represents the population estimated based on ammoniacal nitrogen.
        In RENENSP, this population can vary by year, event and WWTP.
 
        **Load (g/day)** represents the estimated daily mass load entering the wastewater system.
 
        **PNML (mg/day/1000 inhabitants)** represents the population-normalized mass load,
        allowing comparisons between cities, WWTPs and events with different population sizes.
 
        ### Event-Based Monitoring
 
        Event-based campaigns may include samples collected before, during and after major events,
        such as Carnival, São João Festival, New Year's Eve and reference weeks.
        """
    )
 
 
# ============================================================
# DATA EXPLORER
# ============================================================
 
with tab_data:
    st.subheader("Complete Dataset")
 
    st.dataframe(filtered, use_container_width=True)
 
    csv = filtered.to_csv(index=False).encode("utf-8")
 
    st.download_button(
        label="Download filtered data as CSV",
        data=csv,
        file_name="renensp_filtered_data.csv",
        mime="text/csv"
    )
 
 
# ============================================================
# FOOTER
# ============================================================
 
st.markdown("---")
 
st.caption(
    """
    RENENSP Observatory | PROCAD CAPES/SENAD  
    Project Coordinator: Prof. Dr. Jandyson Machado Santos (UFRPE)  
    Platform Developer: Dr. Bruna Ramos de Souza Gomes  
    © 2026 RENENSP Network
    """
)
